name = "liveira-shop"
main = "src/index.js"
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB"
database_name = "liveira-shop"
database_id = "b4c7c78f-4e79-4587-a559-6f794c607bfc"

[[r2_buckets]]
binding = "FILES"
bucket_name = "liveira-shop-files"

[[r2_buckets]]
binding = "CHASE_FILES"
bucket_name = "cf-chase-files"

[[rules]]
type = "Text"
globs = ["**/*.html", "**/*.txt"]
fallthrough = true
